--drop view COMMWEB.VIEW_COMM_DAILY_SUMMARY_HIERARCHY_PIVOTED

--select * from COMMWEB.VIEW_COMM_DAILY_SUMMARY_HIERARCHY_PIVOTED 

CREATE VIEW COMMWEB.VIEW_COMM_DAILY_SUMMARY_HIERARCHY_PIVOTED AS

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'TRAN_TR_REV' AS SOURCE,
    'TRFITL_GROSS_REV' AS DESTINATION,
    TRAN_TR_REV AS VALUE
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE TRAN_TR_REV IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'TRAN_TL_REV',
    'TRFITL_GROSS_REV',
    TRAN_TL_REV
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE TRAN_TL_REV IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'FI_REV',
    'TRFITL_GROSS_REV',
    FI_REV
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE FI_REV IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'INS_REV',
    'TOTAL_GROSS_REV',
    INS_REV
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE INS_REV IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'AMA_FEE_REV',
    'TOTAL_FEE_REV',
    AMA_FEE_REV
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE AMA_FEE_REV IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'UMA_FEE_REV',
    'TOTAL_FEE_REV',
    UMA_FEE_REV
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE UMA_FEE_REV IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'SMA_FEE_REV',
    'TOTAL_FEE_REV',
    SMA_FEE_REV
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE SMA_FEE_REV IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'US_FEE_PMA_REV',
    'TOTAL_FEE_REV',
    US_FEE_PMA_REV
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE US_FEE_PMA_REV IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'PMA_FEE_REV',
    'TOTAL_FEE_REV',
    PMA_FEE_REV
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE PMA_FEE_REV IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'US_FEE_SMA_REV',
    'TOTAL_FEE_REV',
    US_FEE_SMA_REV
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE US_FEE_SMA_REV IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'PMA_NEW_ISSUE_NOPAYOUT_REV',
    'TOTAL_GROSS_REV',
    PMA_NEW_ISSUE_NOPAYOUT_REV
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE PMA_NEW_ISSUE_NOPAYOUT_REV IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'NI_PAYOUT_REV',
    'TOTAL_GROSS_REV',
    NI_PAYOUT_REV
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE NI_PAYOUT_REV IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'REG_FEE_REV',
    'OTH_REV',
    REG_FEE_REV
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE REG_FEE_REV IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'EMP_REG_FEE_REV',
    'OTH_REV',
    EMP_REG_FEE_REV
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE EMP_REG_FEE_REV IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'GIC_COMM_REV',
    'OTH_REV',
    GIC_COMM_REV
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE GIC_COMM_REV IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'TF_FEE_REV',
    'OTH_REV',
    TF_FEE_REV
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE TF_FEE_REV IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'TOTAL_GROSS_REV',
    'NI_NETPAYOUT',
    NI_NETPAYOUT
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE NI_NETPAYOUT IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'TOTAL_GROSS_REV',
    'INS_NETPAYOUT',
    INS_NETPAYOUT
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE INS_NETPAYOUT IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'TOTAL_GROSS_REV',
    'OTH_NETPAYOUT',
    OTH_NETPAYOUT
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE OTH_NETPAYOUT IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'TOTAL_GROSS_REV',
    'TRAN_TR_NETPAYOUT',
    TRAN_TR_NETPAYOUT
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE TRAN_TR_NETPAYOUT IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'TOTAL_GROSS_REV',
    'FI_REV_PAYOUT_PCT',
    FI_REV_PAYOUT_PCT
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE FI_REV_PAYOUT_PCT IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'TOTAL_GROSS_REV',
    'FEE_REV_PAYOUT_PCT',
    FEE_REV_PAYOUT_PCT
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE FEE_REV_PAYOUT_PCT IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'TOTAL_NET_PAYOUT',
    'PMA_EXCESS_TRADE',
    PMA_EXCESS_TRADE
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE PMA_EXCESS_TRADE IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'TOTAL_NET_PAYOUT',
    'DISCOUNT_FEE',
    DISCOUNT_FEE
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE DISCOUNT_FEE IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'TOTAL_NET_PAYOUT',
    'AMA_EXCESS_TRADE',
    AMA_EXCESS_TRADE
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE AMA_EXCESS_TRADE IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'TRFITL_GROSS_REV',
    'TOTAL_GROSS_REV',
    TRFITL_GROSS_REV
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE TRFITL_GROSS_REV IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'TOTAL_FEE_REV',
    'TOTAL_GROSS_REV',
    TRFITL_GROSS_REV
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE TOTAL_FEE_REV IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'OTH_REV',
    'TOTAL_GROSS_REV',
    OTH_REV
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE OTH_REV IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'NI_NETPAYOUT',
    'TOTAL_NET_PAYOUT',
    NI_NETPAYOUT
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE NI_NETPAYOUT IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'INS_NETPAYOUT',
    'TOTAL_NET_PAYOUT',
    INS_NETPAYOUT
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE INS_NETPAYOUT IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'OTH_NETPAYOUT',
    'TOTAL_NET_PAYOUT',
    OTH_NETPAYOUT
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE OTH_NETPAYOUT IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'TRAN_TR_NETPAYOUT',
    'TOTAL_NET_PAYOUT',
    TRAN_TR_NETPAYOUT
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE TRAN_TR_NETPAYOUT IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'FI_REV_PAYOUT_PCT',
    'TOTAL_NET_PAYOUT',
    FI_REV_PAYOUT_PCT
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE FI_REV_PAYOUT_PCT IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'FEE_REV_PAYOUT_PCT',
    'TOTAL_NET_PAYOUT',
    FEE_REV_PAYOUT_PCT
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE FEE_REV_PAYOUT_PCT IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'AMA_EXCESS_TRADE',
    'FINAL_NET_PAYOUT',
    AMA_EXCESS_TRADE
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE AMA_EXCESS_TRADE IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'DISCOUNT_FEE',
    'FINAL_NET_PAYOUT',
    DISCOUNT_FEE
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE DISCOUNT_FEE IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'PMA_EXCESS_TRADE',
    'FINAL_NET_PAYOUT',
    PMA_EXCESS_TRADE
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE PMA_EXCESS_TRADE IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'IA_CODE',
    'TRAN_TR_REV',
    TRAN_TR_REV
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE TRAN_TR_REV IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'IA_CODE',
    'TRAN_TL_REV',
    TRAN_TL_REV
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE TRAN_TL_REV IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'IA_CODE',
    'FI_REV',
    FI_REV
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE FI_REV IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'IA_CODE',
    'INS_REV',
    INS_REV
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE INS_REV IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'IA_CODE',
    'AMA_FEE_REV',
    AMA_FEE_REV
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE AMA_FEE_REV IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'IA_CODE',
    'UMA_FEE_REV',
    UMA_FEE_REV
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE UMA_FEE_REV IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'IA_CODE',
    'SMA_FEE_REV',
    SMA_FEE_REV
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE SMA_FEE_REV IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'IA_CODE',
    'US_FEE_PMA_REV',
    US_FEE_PMA_REV
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE US_FEE_PMA_REV IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'IA_CODE',
    'PMA_FEE_REV',
    PMA_FEE_REV
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE PMA_FEE_REV IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'IA_CODE',
    'US_FEE_SMA_REV',
    US_FEE_SMA_REV
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE US_FEE_SMA_REV IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'IA_CODE',
    'PMA_NEW_ISSUE_NOPAYOUT_REV',
    PMA_NEW_ISSUE_NOPAYOUT_REV
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE PMA_NEW_ISSUE_NOPAYOUT_REV IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'IA_CODE',
    'NI_PAYOUT_REV',
    NI_PAYOUT_REV
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE NI_PAYOUT_REV IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'IA_CODE',
    'REG_FEE_REV',
    REG_FEE_REV
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE REG_FEE_REV IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'IA_CODE',
    'EMP_REG_FEE_REV',
    EMP_REG_FEE_REV
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE EMP_REG_FEE_REV IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'IA_CODE',
    'GIC_COMM_REV',
    GIC_COMM_REV
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE GIC_COMM_REV IS NOT NULL

UNION ALL

SELECT
    IA_CODE,
    BUSINESS_DATE,
	TO_IA_CODE,
    'IA_CODE',
    'TF_FEE_REV',
    TF_FEE_REV
FROM COMMWEB.COMM_DAILY_SUMMARY
WHERE TF_FEE_REV IS NOT NULL;
